//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Admin
{
    public partial class AddBranch
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtBranchName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBranchName;

        /// <summary>
        /// rfvBranchName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBranchName;

        /// <summary>
        /// txtBranchCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtBranchCode;

        /// <summary>
        /// rfvBranchCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBranchCode;

        /// <summary>
        /// txtCity control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;

        /// <summary>
        /// txtPhoneNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;

        /// <summary>
        /// txtAddress control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// btnAddBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddBranch;
    }
}
