//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Admin
{
    public partial class AddStationary
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtLocationCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLocationCode;

        /// <summary>
        /// rfvLocationCode control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLocationCode;

        /// <summary>
        /// txtDescription control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDescription;

        /// <summary>
        /// btnCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCancel;

        /// <summary>
        /// btnAddStationary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddStationary;
    }
}
