//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Admin
{


    public partial class Dashboard
    {

        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblAdminName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblAdminName;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// lblPendingOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingOrders;

        /// <summary>
        /// lblLowStockCount control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLowStockCount;

        /// <summary>
        /// lblPendingRequests control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPendingRequests;

        /// <summary>
        /// lblActiveUsers control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblActiveUsers;

        /// <summary>
        /// lblTotalBranches control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblTotalBranches;
    }
}
