//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Admin
{
    public partial class ManageBranches
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// btnAddNewBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnAddNewBranch;

        /// <summary>
        /// btnBackToDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackToDashboard;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSearch;

        /// <summary>
        /// btnSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// btnClearSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearSearch;

        /// <summary>
        /// lblSearchResults control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblSearchResults;

        /// <summary>
        /// gvBranches control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvBranches;
    }
}
