//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Customer
{
    public partial class Dashboard
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// lblCustomerName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCustomerName;

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogout;

        /// <summary>
        /// lblEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblEmail;

        /// <summary>
        /// lblFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblFullName;

        /// <summary>
        /// lblBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblBranch;

        /// <summary>
        /// lblPhoneNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblPhoneNumber;

        /// <summary>
        /// lblCreatedDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblCreatedDate;

        /// <summary>
        /// lblLastLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblLastLogin;
    }
}
