//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Customer
{
    public partial class MyOrders
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// btnBackToDashboard control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnBackToDashboard;

        /// <summary>
        /// gvOrders control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrders;

        /// <summary>
        /// ddlStatusFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlStatusFilter;

        /// <summary>
        /// btnFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnFilter;

        /// <summary>
        /// btnClearFilter control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnClearFilter;

        /// <summary>
        /// pnlOrderDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlOrderDetails;

        /// <summary>
        /// lblOrderId control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderId;

        /// <summary>
        /// lblOrderDate control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderDate;

        /// <summary>
        /// lblOrderStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderStatus;

        /// <summary>
        /// lblOrderNotes control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderNotes;

        /// <summary>
        /// gvOrderItems control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView gvOrderItems;

        /// <summary>
        /// lblOrderTotal control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblOrderTotal;

        /// <summary>
        /// btnCloseDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnCloseDetails;
    }
}
