//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagementSystem.UI.Guest
{
    public partial class Register
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// pnlMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlMessage;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;

        /// <summary>
        /// txtFullName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFullName;

        /// <summary>
        /// txtEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;

        /// <summary>
        /// rfvEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEmail;

        /// <summary>
        /// revEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>
        /// txtPhoneNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;

        /// <summary>
        /// ddlBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList ddlBranch;

        /// <summary>
        /// rfvBranch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBranch;

        /// <summary>
        /// txtPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtPassword;

        /// <summary>
        /// rfvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvPassword;

        /// <summary>
        /// txtConfirmPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtConfirmPassword;

        /// <summary>
        /// cvPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.CompareValidator cvPassword;

        /// <summary>
        /// btnRegister control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnRegister;
    }
}
